export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'surface-raised': 'var(--color-surface-raised)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-inverse': 'var(--color-text-inverse)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-secondary': 'var(--color-accent-secondary)',
        cta: 'var(--color-cta)',
        'cta-hover': 'var(--color-cta-hover)',
        'cta-text': 'var(--color-cta-text)',
        danger: 'var(--color-danger)',
        'danger-hover': 'var(--color-danger-hover)',
        success: 'var(--color-success)',
        border: 'var(--color-border)',
        'sidebar-bg': 'var(--color-sidebar-bg)',
        'sidebar-text': 'var(--color-sidebar-text)',
        'sidebar-active': 'var(--color-sidebar-active)',
        'sidebar-hover': 'var(--color-sidebar-hover)',
        'header-bg': 'var(--color-header-bg)',
        'header-text': 'var(--color-header-text)',
        'input-bg': 'var(--color-input-bg)',
        'input-border': 'var(--color-input-border)',
        'chip-accent-bg': 'var(--color-chip-accent-bg)',
        'chip-accent-text': 'var(--color-chip-accent-text)',
        'chip-olive-bg': 'var(--color-chip-olive-bg)',
        'chip-olive-text': 'var(--color-chip-olive-text)',
        'chip-amber-bg': 'var(--color-chip-amber-bg)',
        'chip-amber-text': 'var(--color-chip-amber-text)',
        'chip-warm-bg': 'var(--color-chip-warm-bg)',
        'chip-warm-text': 'var(--color-chip-warm-text)',
        'chip-sky-bg': 'var(--color-chip-sky-bg)',
        'chip-sky-text': 'var(--color-chip-sky-text)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        card: 'var(--color-card-shadow)',
        'card-lg': 'var(--color-card-shadow-lg)',
        'accent-glow': 'var(--color-accent-glow)',
        glass: 'var(--color-glass-shadow)',
      },
    },
  },
  plugins: [],
}
